//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNotificacion
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceNotificacion.zpp_notificaciones")]
    public interface zpp_notificaciones
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceNotificacion.ZppHuNotifBapiEResponse1> ZppHuNotifBapiEAsync(ServiceNotificacion.ZppHuNotifBapiERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZppHuNotifBapiE
    {
        
        private Bapiret2[] retField;
        
        private Bapiret2[] ret2Field;
        
        private string w1HuExidField;
        
        private string w1PackMatField;
        
        private string w1PlantField;
        
        private string w2BudatField;
        
        private string w2HoraField;
        
        private string w2PlnumField;
        
        private string w2PlwerkField;
        
        private string w2VeridField;
        
        private string w3BatchField;
        
        private string w3MaterialField;
        
        private string w3PackQtyField;
        
        private bool w3PackQtyFieldSpecified;
        
        private string w3Plant2Field;
        
        private string w3StgeLoc2Field;
        
        private string wBolsaField;
        
        private string wCantenvField;
        
        private string wEnvaseField;
        
        private string wEnvase2Field;
        
        private string wFechaSemiField;
        
        private string wFundaField;
        
        private string wPaletField;
        
        private string wPesoField;
        
        private string wPesobField;
        
        private string wPrimerLoteField;
        
        private string wSelloField;
        
        private string wTurnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Ret
        {
            get
            {
                return this.retField;
            }
            set
            {
                this.retField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Ret2
        {
            get
            {
                return this.ret2Field;
            }
            set
            {
                this.ret2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string W1HuExid
        {
            get
            {
                return this.w1HuExidField;
            }
            set
            {
                this.w1HuExidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string W1PackMat
        {
            get
            {
                return this.w1PackMatField;
            }
            set
            {
                this.w1PackMatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string W1Plant
        {
            get
            {
                return this.w1PlantField;
            }
            set
            {
                this.w1PlantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string W2Budat
        {
            get
            {
                return this.w2BudatField;
            }
            set
            {
                this.w2BudatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string W2Hora
        {
            get
            {
                return this.w2HoraField;
            }
            set
            {
                this.w2HoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string W2Plnum
        {
            get
            {
                return this.w2PlnumField;
            }
            set
            {
                this.w2PlnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string W2Plwerk
        {
            get
            {
                return this.w2PlwerkField;
            }
            set
            {
                this.w2PlwerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string W2Verid
        {
            get
            {
                return this.w2VeridField;
            }
            set
            {
                this.w2VeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string W3Batch
        {
            get
            {
                return this.w3BatchField;
            }
            set
            {
                this.w3BatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string W3Material
        {
            get
            {
                return this.w3MaterialField;
            }
            set
            {
                this.w3MaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string W3PackQty
        {
            get
            {
                return this.w3PackQtyField;
            }
            set
            {
                this.w3PackQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool W3PackQtySpecified
        {
            get
            {
                return this.w3PackQtyFieldSpecified;
            }
            set
            {
                this.w3PackQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string W3Plant2
        {
            get
            {
                return this.w3Plant2Field;
            }
            set
            {
                this.w3Plant2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string W3StgeLoc2
        {
            get
            {
                return this.w3StgeLoc2Field;
            }
            set
            {
                this.w3StgeLoc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string WBolsa
        {
            get
            {
                return this.wBolsaField;
            }
            set
            {
                this.wBolsaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string WCantenv
        {
            get
            {
                return this.wCantenvField;
            }
            set
            {
                this.wCantenvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string WEnvase
        {
            get
            {
                return this.wEnvaseField;
            }
            set
            {
                this.wEnvaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string WEnvase2
        {
            get
            {
                return this.wEnvase2Field;
            }
            set
            {
                this.wEnvase2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string WFechaSemi
        {
            get
            {
                return this.wFechaSemiField;
            }
            set
            {
                this.wFechaSemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string WFunda
        {
            get
            {
                return this.wFundaField;
            }
            set
            {
                this.wFundaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string WPalet
        {
            get
            {
                return this.wPaletField;
            }
            set
            {
                this.wPaletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string WPeso
        {
            get
            {
                return this.wPesoField;
            }
            set
            {
                this.wPesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string WPesob
        {
            get
            {
                return this.wPesobField;
            }
            set
            {
                this.wPesobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string WPrimerLote
        {
            get
            {
                return this.wPrimerLoteField;
            }
            set
            {
                this.wPrimerLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string WSello
        {
            get
            {
                return this.wSelloField;
            }
            set
            {
                this.wSelloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string WTurno
        {
            get
            {
                return this.wTurnoField;
            }
            set
            {
                this.wTurnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2
    {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo
        {
            get
            {
                return this.logNoField;
            }
            set
            {
                this.logNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo
        {
            get
            {
                return this.logMsgNoField;
            }
            set
            {
                this.logMsgNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1
        {
            get
            {
                return this.messageV1Field;
            }
            set
            {
                this.messageV1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2
        {
            get
            {
                return this.messageV2Field;
            }
            set
            {
                this.messageV2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3
        {
            get
            {
                return this.messageV3Field;
            }
            set
            {
                this.messageV3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4
        {
            get
            {
                return this.messageV4Field;
            }
            set
            {
                this.messageV4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int Row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string System2
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZppHuNotifBapiEResponse
    {
        
        private string docVField;
        
        private int errField;
        
        private int err2Field;
        
        private int err3Field;
        
        private int err4Field;
        
        private int err5Field;
        
        private int err6Field;
        
        private int err7Field;
        
        private int errNotifField;
        
        private Bapiret2[] retField;
        
        private Bapiret2[] ret2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DocV
        {
            get
            {
                return this.docVField;
            }
            set
            {
                this.docVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Err
        {
            get
            {
                return this.errField;
            }
            set
            {
                this.errField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Err2
        {
            get
            {
                return this.err2Field;
            }
            set
            {
                this.err2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Err3
        {
            get
            {
                return this.err3Field;
            }
            set
            {
                this.err3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int Err4
        {
            get
            {
                return this.err4Field;
            }
            set
            {
                this.err4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int Err5
        {
            get
            {
                return this.err5Field;
            }
            set
            {
                this.err5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int Err6
        {
            get
            {
                return this.err6Field;
            }
            set
            {
                this.err6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int Err7
        {
            get
            {
                return this.err7Field;
            }
            set
            {
                this.err7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int ErrNotif
        {
            get
            {
                return this.errNotifField;
            }
            set
            {
                this.errNotifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Ret
        {
            get
            {
                return this.retField;
            }
            set
            {
                this.retField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Ret2
        {
            get
            {
                return this.ret2Field;
            }
            set
            {
                this.ret2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZppHuNotifBapiERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceNotificacion.ZppHuNotifBapiE ZppHuNotifBapiE;
        
        public ZppHuNotifBapiERequest()
        {
        }
        
        public ZppHuNotifBapiERequest(ServiceNotificacion.ZppHuNotifBapiE ZppHuNotifBapiE)
        {
            this.ZppHuNotifBapiE = ZppHuNotifBapiE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZppHuNotifBapiEResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceNotificacion.ZppHuNotifBapiEResponse ZppHuNotifBapiEResponse;
        
        public ZppHuNotifBapiEResponse1()
        {
        }
        
        public ZppHuNotifBapiEResponse1(ServiceNotificacion.ZppHuNotifBapiEResponse ZppHuNotifBapiEResponse)
        {
            this.ZppHuNotifBapiEResponse = ZppHuNotifBapiEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface zpp_notificacionesChannel : ServiceNotificacion.zpp_notificaciones, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class zpp_notificacionesClient : System.ServiceModel.ClientBase<ServiceNotificacion.zpp_notificaciones>, ServiceNotificacion.zpp_notificaciones
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public zpp_notificacionesClient() : 
                base(zpp_notificacionesClient.GetDefaultBinding(), zpp_notificacionesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.zpp_notificaciones.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zpp_notificacionesClient(EndpointConfiguration endpointConfiguration) : 
                base(zpp_notificacionesClient.GetBindingForEndpoint(endpointConfiguration), zpp_notificacionesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zpp_notificacionesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(zpp_notificacionesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zpp_notificacionesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(zpp_notificacionesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zpp_notificacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceNotificacion.ZppHuNotifBapiEResponse1> ServiceNotificacion.zpp_notificaciones.ZppHuNotifBapiEAsync(ServiceNotificacion.ZppHuNotifBapiERequest request)
        {
            return base.Channel.ZppHuNotifBapiEAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceNotificacion.ZppHuNotifBapiEResponse1> ZppHuNotifBapiEAsync(ServiceNotificacion.ZppHuNotifBapiE ZppHuNotifBapiE)
        {
            ServiceNotificacion.ZppHuNotifBapiERequest inValue = new ServiceNotificacion.ZppHuNotifBapiERequest();
            inValue.ZppHuNotifBapiE = ZppHuNotifBapiE;
            return ((ServiceNotificacion.zpp_notificaciones)(this)).ZppHuNotifBapiEAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.zpp_notificaciones))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.zpp_notificaciones))
            {
                return new System.ServiceModel.EndpointAddress("http://aplaco2.aconcaguafoods.cl:8000/sap/bc/srt/rfc/sap/zpp_notificaciones/500/z" +
                        "pp_notificaciones/zpp_notificaciones");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return zpp_notificacionesClient.GetBindingForEndpoint(EndpointConfiguration.zpp_notificaciones);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return zpp_notificacionesClient.GetEndpointAddress(EndpointConfiguration.zpp_notificaciones);
        }
        
        public enum EndpointConfiguration
        {
            
            zpp_notificaciones,
        }
    }
}
