//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMoverUmas
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReferenceMoverUmas.zmm_fnc_mover_umas")]
    public interface zmm_fnc_mover_umas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceMoverUmas.ZmmWbsMovimientosResponse1> ZmmWbsMovimientosAsync(ServiceReferenceMoverUmas.ZmmWbsMovimientosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmWbsMovimientos
    {
        
        private string wLgortField;
        
        private string wUmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WLgort
        {
            get
            {
                return this.wLgortField;
            }
            set
            {
                this.wLgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WUma
        {
            get
            {
                return this.wUmaField;
            }
            set
            {
                this.wUmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmWbsMovimientosResponse
    {
        
        private string wDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WDoc
        {
            get
            {
                return this.wDocField;
            }
            set
            {
                this.wDocField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmmWbsMovimientosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReferenceMoverUmas.ZmmWbsMovimientos ZmmWbsMovimientos;
        
        public ZmmWbsMovimientosRequest()
        {
        }
        
        public ZmmWbsMovimientosRequest(ServiceReferenceMoverUmas.ZmmWbsMovimientos ZmmWbsMovimientos)
        {
            this.ZmmWbsMovimientos = ZmmWbsMovimientos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmmWbsMovimientosResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReferenceMoverUmas.ZmmWbsMovimientosResponse ZmmWbsMovimientosResponse;
        
        public ZmmWbsMovimientosResponse1()
        {
        }
        
        public ZmmWbsMovimientosResponse1(ServiceReferenceMoverUmas.ZmmWbsMovimientosResponse ZmmWbsMovimientosResponse)
        {
            this.ZmmWbsMovimientosResponse = ZmmWbsMovimientosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface zmm_fnc_mover_umasChannel : ServiceReferenceMoverUmas.zmm_fnc_mover_umas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class zmm_fnc_mover_umasClient : System.ServiceModel.ClientBase<ServiceReferenceMoverUmas.zmm_fnc_mover_umas>, ServiceReferenceMoverUmas.zmm_fnc_mover_umas
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public zmm_fnc_mover_umasClient() : 
                base(zmm_fnc_mover_umasClient.GetDefaultBinding(), zmm_fnc_mover_umasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZMM_FNC_MOVER_UMAS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zmm_fnc_mover_umasClient(EndpointConfiguration endpointConfiguration) : 
                base(zmm_fnc_mover_umasClient.GetBindingForEndpoint(endpointConfiguration), zmm_fnc_mover_umasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zmm_fnc_mover_umasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(zmm_fnc_mover_umasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zmm_fnc_mover_umasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(zmm_fnc_mover_umasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zmm_fnc_mover_umasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceMoverUmas.ZmmWbsMovimientosResponse1> ServiceReferenceMoverUmas.zmm_fnc_mover_umas.ZmmWbsMovimientosAsync(ServiceReferenceMoverUmas.ZmmWbsMovimientosRequest request)
        {
            return base.Channel.ZmmWbsMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoverUmas.ZmmWbsMovimientosResponse1> ZmmWbsMovimientosAsync(ServiceReferenceMoverUmas.ZmmWbsMovimientos ZmmWbsMovimientos)
        {
            ServiceReferenceMoverUmas.ZmmWbsMovimientosRequest inValue = new ServiceReferenceMoverUmas.ZmmWbsMovimientosRequest();
            inValue.ZmmWbsMovimientos = ZmmWbsMovimientos;
            return ((ServiceReferenceMoverUmas.zmm_fnc_mover_umas)(this)).ZmmWbsMovimientosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZMM_FNC_MOVER_UMAS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZMM_FNC_MOVER_UMAS))
            {
                return new System.ServiceModel.EndpointAddress("http://aplaco2.aconcaguafoods.cl:8000/sap/bc/srt/rfc/sap/zmm_fnc_mover_umas/500/z" +
                        "mm_fnc_mover_umas/zmm_fnc_mover_umas");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return zmm_fnc_mover_umasClient.GetBindingForEndpoint(EndpointConfiguration.ZMM_FNC_MOVER_UMAS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return zmm_fnc_mover_umasClient.GetEndpointAddress(EndpointConfiguration.ZMM_FNC_MOVER_UMAS);
        }
        
        public enum EndpointConfiguration
        {
            
            ZMM_FNC_MOVER_UMAS,
        }
    }
}
