//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceOT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReferenceOT.ZWS_ETIQUETADO0008")]
    public interface ZWS_ETIQUETADO0008
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceOT.ZwsPpEtiquetado0008Response1> ZwsPpEtiquetado0008Async(ServiceReferenceOT.ZwsPpEtiquetado0008Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsPpEtiquetado0008
    {
        
        private string wBwlvsField;
        
        private string wFechaField;
        
        private string wLgortField;
        
        private string wNlplaField;
        
        private string wNltypField;
        
        private string wSquitField;
        
        private string wTipoField;
        
        private string wUmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WBwlvs
        {
            get
            {
                return this.wBwlvsField;
            }
            set
            {
                this.wBwlvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WFecha
        {
            get
            {
                return this.wFechaField;
            }
            set
            {
                this.wFechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WLgort
        {
            get
            {
                return this.wLgortField;
            }
            set
            {
                this.wLgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string WNlpla
        {
            get
            {
                return this.wNlplaField;
            }
            set
            {
                this.wNlplaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string WNltyp
        {
            get
            {
                return this.wNltypField;
            }
            set
            {
                this.wNltypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string WSquit
        {
            get
            {
                return this.wSquitField;
            }
            set
            {
                this.wSquitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WTipo
        {
            get
            {
                return this.wTipoField;
            }
            set
            {
                this.wTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WUma
        {
            get
            {
                return this.wUmaField;
            }
            set
            {
                this.wUmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsPpEtiquetado0008Response
    {
        
        private string wDocField;
        
        private string wMensajeField;
        
        private string wTanumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WDoc
        {
            get
            {
                return this.wDocField;
            }
            set
            {
                this.wDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WMensaje
        {
            get
            {
                return this.wMensajeField;
            }
            set
            {
                this.wMensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WTanum
        {
            get
            {
                return this.wTanumField;
            }
            set
            {
                this.wTanumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsPpEtiquetado0008Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReferenceOT.ZwsPpEtiquetado0008 ZwsPpEtiquetado0008;
        
        public ZwsPpEtiquetado0008Request()
        {
        }
        
        public ZwsPpEtiquetado0008Request(ServiceReferenceOT.ZwsPpEtiquetado0008 ZwsPpEtiquetado0008)
        {
            this.ZwsPpEtiquetado0008 = ZwsPpEtiquetado0008;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsPpEtiquetado0008Response1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReferenceOT.ZwsPpEtiquetado0008Response ZwsPpEtiquetado0008Response;
        
        public ZwsPpEtiquetado0008Response1()
        {
        }
        
        public ZwsPpEtiquetado0008Response1(ServiceReferenceOT.ZwsPpEtiquetado0008Response ZwsPpEtiquetado0008Response)
        {
            this.ZwsPpEtiquetado0008Response = ZwsPpEtiquetado0008Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZWS_ETIQUETADO0008Channel : ServiceReferenceOT.ZWS_ETIQUETADO0008, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZWS_ETIQUETADO0008Client : System.ServiceModel.ClientBase<ServiceReferenceOT.ZWS_ETIQUETADO0008>, ServiceReferenceOT.ZWS_ETIQUETADO0008
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZWS_ETIQUETADO0008Client() : 
                base(ZWS_ETIQUETADO0008Client.GetDefaultBinding(), ZWS_ETIQUETADO0008Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZWS_ETIQUETADO0008.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0008Client(EndpointConfiguration endpointConfiguration) : 
                base(ZWS_ETIQUETADO0008Client.GetBindingForEndpoint(endpointConfiguration), ZWS_ETIQUETADO0008Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0008Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZWS_ETIQUETADO0008Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0008Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZWS_ETIQUETADO0008Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0008Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceOT.ZwsPpEtiquetado0008Response1> ServiceReferenceOT.ZWS_ETIQUETADO0008.ZwsPpEtiquetado0008Async(ServiceReferenceOT.ZwsPpEtiquetado0008Request request)
        {
            return base.Channel.ZwsPpEtiquetado0008Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceOT.ZwsPpEtiquetado0008Response1> ZwsPpEtiquetado0008Async(ServiceReferenceOT.ZwsPpEtiquetado0008 ZwsPpEtiquetado0008)
        {
            ServiceReferenceOT.ZwsPpEtiquetado0008Request inValue = new ServiceReferenceOT.ZwsPpEtiquetado0008Request();
            inValue.ZwsPpEtiquetado0008 = ZwsPpEtiquetado0008;
            return ((ServiceReferenceOT.ZWS_ETIQUETADO0008)(this)).ZwsPpEtiquetado0008Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZWS_ETIQUETADO0008))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZWS_ETIQUETADO0008))
            {
                return new System.ServiceModel.EndpointAddress("http://aplaco2.aconcaguafoods.cl:8000/sap/bc/srt/rfc/sap/zws_etiquetado0008/500/z" +
                        "ws_etiquetado0008/zws_etiquetado0008");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZWS_ETIQUETADO0008Client.GetBindingForEndpoint(EndpointConfiguration.ZWS_ETIQUETADO0008);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZWS_ETIQUETADO0008Client.GetEndpointAddress(EndpointConfiguration.ZWS_ETIQUETADO0008);
        }
        
        public enum EndpointConfiguration
        {
            
            ZWS_ETIQUETADO0008,
        }
    }
}
