//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceActualizaFechaCodificado
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006")]
    public interface ZWS_ETIQUETADO0006
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Response1> ZwsPpEtiquetado0006Async(ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsPpEtiquetado0006
    {
        
        private decimal wCantidadField;
        
        private bool wCantidadFieldSpecified;
        
        private string wEnvaseField;
        
        private string wExidvField;
        
        private string wFechaSemiField;
        
        private string wFecha_1Field;
        
        private string wHoraField;
        
        private string wLineaField;
        
        private string wLoteField;
        
        private string wMaterialField;
        
        private string wPlnumField;
        
        private string wTipoField;
        
        private string wVeridField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal WCantidad
        {
            get
            {
                return this.wCantidadField;
            }
            set
            {
                this.wCantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WCantidadSpecified
        {
            get
            {
                return this.wCantidadFieldSpecified;
            }
            set
            {
                this.wCantidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WEnvase
        {
            get
            {
                return this.wEnvaseField;
            }
            set
            {
                this.wEnvaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WExidv
        {
            get
            {
                return this.wExidvField;
            }
            set
            {
                this.wExidvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string WFechaSemi
        {
            get
            {
                return this.wFechaSemiField;
            }
            set
            {
                this.wFechaSemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string WFecha_1
        {
            get
            {
                return this.wFecha_1Field;
            }
            set
            {
                this.wFecha_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string WHora
        {
            get
            {
                return this.wHoraField;
            }
            set
            {
                this.wHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WLinea
        {
            get
            {
                return this.wLineaField;
            }
            set
            {
                this.wLineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WLote
        {
            get
            {
                return this.wLoteField;
            }
            set
            {
                this.wLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string WMaterial
        {
            get
            {
                return this.wMaterialField;
            }
            set
            {
                this.wMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string WPlnum
        {
            get
            {
                return this.wPlnumField;
            }
            set
            {
                this.wPlnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string WTipo
        {
            get
            {
                return this.wTipoField;
            }
            set
            {
                this.wTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string WVerid
        {
            get
            {
                return this.wVeridField;
            }
            set
            {
                this.wVeridField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsPpEtiquetado0006Response
    {
        
        private string wDocField;
        
        private string wMensajesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WDoc
        {
            get
            {
                return this.wDocField;
            }
            set
            {
                this.wDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WMensajes
        {
            get
            {
                return this.wMensajesField;
            }
            set
            {
                this.wMensajesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsPpEtiquetado0006Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006 ZwsPpEtiquetado0006;
        
        public ZwsPpEtiquetado0006Request()
        {
        }
        
        public ZwsPpEtiquetado0006Request(ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006 ZwsPpEtiquetado0006)
        {
            this.ZwsPpEtiquetado0006 = ZwsPpEtiquetado0006;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsPpEtiquetado0006Response1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Response ZwsPpEtiquetado0006Response;
        
        public ZwsPpEtiquetado0006Response1()
        {
        }
        
        public ZwsPpEtiquetado0006Response1(ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Response ZwsPpEtiquetado0006Response)
        {
            this.ZwsPpEtiquetado0006Response = ZwsPpEtiquetado0006Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZWS_ETIQUETADO0006Channel : ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZWS_ETIQUETADO0006Client : System.ServiceModel.ClientBase<ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006>, ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZWS_ETIQUETADO0006Client() : 
                base(ZWS_ETIQUETADO0006Client.GetDefaultBinding(), ZWS_ETIQUETADO0006Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZWS_ETIQUETADO0006.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0006Client(EndpointConfiguration endpointConfiguration) : 
                base(ZWS_ETIQUETADO0006Client.GetBindingForEndpoint(endpointConfiguration), ZWS_ETIQUETADO0006Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0006Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZWS_ETIQUETADO0006Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0006Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZWS_ETIQUETADO0006Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZWS_ETIQUETADO0006Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Response1> ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006.ZwsPpEtiquetado0006Async(ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Request request)
        {
            return base.Channel.ZwsPpEtiquetado0006Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Response1> ZwsPpEtiquetado0006Async(ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006 ZwsPpEtiquetado0006)
        {
            ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Request inValue = new ServiceActualizaFechaCodificado.ZwsPpEtiquetado0006Request();
            inValue.ZwsPpEtiquetado0006 = ZwsPpEtiquetado0006;
            return ((ServiceActualizaFechaCodificado.ZWS_ETIQUETADO0006)(this)).ZwsPpEtiquetado0006Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZWS_ETIQUETADO0006))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZWS_ETIQUETADO0006))
            {
                return new System.ServiceModel.EndpointAddress("http://aplaco2.aconcaguafoods.cl:8000/sap/bc/srt/rfc/sap/zws_etiquetado0006/500/z" +
                        "ws_etiquetado0006/zws_etiquetado0006");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZWS_ETIQUETADO0006Client.GetBindingForEndpoint(EndpointConfiguration.ZWS_ETIQUETADO0006);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZWS_ETIQUETADO0006Client.GetEndpointAddress(EndpointConfiguration.ZWS_ETIQUETADO0006);
        }
        
        public enum EndpointConfiguration
        {
            
            ZWS_ETIQUETADO0006,
        }
    }
}
